#Here we will try to guess a number randomly generated by computer
import random

def guess(x):
    guess=0
    random_number= random.randint(1,x)
    while guess != random_number:
        guess= int(input(f"Enter the number you guessed between  range 1 to {x}: "))
        if guess > random_number:
            print("try Again, it's high than the number to be guessed ")
        elif guess< random_number:
            print("try agian, It's low than the number to be guessed ")
        else:
            print(f"congratulations! the number is {guess} is correctly guessed by you")


guess(15)





# Here computer will Guess the number    

def computer_guess(x):
    low = 1
    high= x
    user_feedback= ""
    while user_feedback != "c":
        if low != high: 
            guessed_number= random.randint(low,high)
        else:
            guessed_number = high

        user_feedback=input(f"Give your feedback about computer guessed number {guessed_number}, h(high) l(low),c(correct)").lower()

        if user_feedback == "h":
            high= guessed_number-1

        elif user_feedback == "l":
            low = guessed_number+1
        
        
    print(f" Wow ! computer guessed the correct number {guessed_number} ")

computer_guess(200)
 



